version: 2.1
workflows:
  main:
    jobs:
      - test

jobs:
  test:
    docker:
      - image: cimg/python:3.6.7
    steps:
      - checkout
      - run:
          name: "Download Dependancies"
          command: |
            make
            make test-readme
            make ci
